package com.wallet.service.prototype.enums;


import com.wallet.service.prototype.dtos.CurrencyResponse;
import lombok.Getter;

@Getter
public enum Currency {
    AED("AED", "UAE Dirham", ""),
    AFN("AFN", "Afghani", "؋"),
    ALL("ALL", "Lek Lek", "Lek"),
    AMD("AMD", "Armenian Dram", ""),
    ANG("ANG", "Netherlands Antillian Guilder", "ƒ"),
    AOA("AOA", "Kwanza", ""),
    ARS("ARS", "Argentine Peso", "$"),
    AUD("AUD", "Australian Dollar", "$"),
    AWG("AWG", "Aruban Guilder", "ƒ"),
    AZN("AZN", "Azerbaijanian Manat", "ман"),
    BAM("BAM", "Convertible Marks", "KM"),
    BBD("BBD", "Barbados Dollar", "$"),
    BDT("BDT", "Taka", ""),
    BGN("BGN", "Bulgarian Lev", "лв"),
    BHD("BHD", "Bahraini Dinar", ""),
    BIF("BIF", "Burundi Franc", ""),
    BMD("BMD", "Bermudian Dollar", "$"),
    BND("BND", "Brunei Dollar", "$"),
    BOB("BOB", "BOV Boliviano Mvdol", "$b"),
    BRL("BRL", "Brazilian Real", "R$"),
    BSD("BSD", "Bahamian Dollar", "$"),
    BWP("BWP", "Pula", "P"),
    BYR("BYR", "Belarussian Ruble", "p."),
    BZD("BZD", "Belize Dollar", "BZ$"),
    CAD("CAD", "Canadian Dollar", "$"),
    CDF("CDF", "Congolese Franc", ""),
    CHF("CHF", "Swiss Franc	CHF", "CHF"),
    CLP("CLP", "Chilean Peso Unidades de fomento", "$"),
    CNY("CNY", "Yuan Renminbi", "¥"),
    COP("COP", "COU Colombian Peso Unidad de Valor Real", "$"),
    CRC("CRC", "Costa Rican Colon", "₡"),
    CUP("CUP", "Cuban Peso Peso Convertible", "₱"),
    CVE("CVE", "Cape Verde Escudo", ""),
    CZK("CZK", "Czech Koruna", "Kč"),
    DJF("DJF", "Djibouti Franc", ""),
    DKK("DKK", "Danish Krone", "kr"),
    DOP("DOP", "Dominican Peso", "RD$"),
    DZD("DZD", "Algerian Dinar", ""),
    EEK("EEK", "Kroon", ""),
    EGP("EGP", "Egyptian Pound", "£"),
    ERN("ERN", "Nakfa", ""),
    ETB("ETB", "Ethiopian Birr", ""),
    EUR("EUR", "Euro", "€"),
    FJD("FJD", "Fiji Dollar", "$"),
    FKP("FKP", "Falkland Islands Pound", "£"),
    GBP("GBP", "Pound Sterling", "£"),
    GEL("GEL", "Lari", ""),
    GHS("GHS", "Cedi", "¢"),
    GIP("GIP", "Gibraltar Pound", "£"),
    GMD("GMD", "Dalasi", ""),
    GNF("GNF", "Guinea Franc", ""),
    GTQ("GTQ", "Quetzal", "Q"),
    GYD("GYD", "Guyana Dollar", "$"),
    HKD("HKD", "Hong Kong Dollar", "$"),
    HNL("HNL", "Lempira", "L"),
    HRK("HRK", "Croatian Kuna", "kn"),
    HTG("HTG", "USD Gourde US Dollar", ""),
    HUF("HUF", "Forint", "Ft"),
    IDR("IDR", "Rupiah	Rp", "Rp"),
    ILS("ILS", "New Israeli Sheqel", "₪"),
    INR("INR", "Indian Rupee", ""),
    IQD("IQD", "Iraqi Dinar", ""),
    IRR("IRR", "Iranian Rial", "﷼"),
    ISK("ISK", "Iceland Krona", "kr"),
    JMD("JMD", "Jamaican Dollar", "J$"),
    JOD("JOD", "Jordanian Dinar", ""),
    JPY("JPY", "Yen", "¥"),
    KES("KES", "Kenyan Shilling", ""),
    KGS("KGS", "Som", "лв"),
    KHR("KHR", "Riel", "៛"),
    KMF("KMF", "Comoro Franc", ""),
    KPW("KPW", "North Korean Won", "₩"),
    KRW("KRW", "Won", "₩"),
    KWD("KWD", "Kuwaiti Dinar", ""),
    KYD("KYD", "Cayman Islands Dollar", "$"),
    KZT("KZT", "Tenge", "лв"),
    LAK("LAK", "Kip", "₭"),
    LBP("LBP", "Lebanese Pound", "£"),
    LKR("LKR", "Sri Lanka Rupee", "₨"),
    LRD("LRD", "Liberian Dollar", "$"),
    LTL("LTL", "Lithuanian Litas", "Lt"),
    LVL("LVL", "Latvian Lats", "Ls"),
    LYD("LYD", "Libyan Dinar", ""),
    MAD("MAD", "Moroccan Dirham", ""),
    MDL("MDL", "Moldovan Leu", ""),
    MGA("MGA", "Malagasy Ariary", ""),
    MKD("MKD", "Denar", "ден"),
    MMK("MMK", "Kyat", ""),
    MNT("MNT", "Tugrik", "₮"),
    MOP("MOP", "Pataca", ""),
    MRO("MRO", "Ouguiya", ""),
    MUR("MUR", "Mauritius Rupee", "₨"),
    MVR("MVR", "Rufiyaa", ""),
    MWK("MWK", "Kwacha", ""),
    MXN("MXN", "Mexican Peso Mexican Unidad de Inversion (UDI)", "$"),
    MYR("MYR", "Malaysian Ringgit", "RM"),
    MZN("MZN", "Metical MT", "MT"),
    NGN("NGN", "Naira", "₦"),
    NIO("NIO", "Cordoba Oro", "C$"),
    NOK("NOK", "Norwegian Krone", "kr"),
    NPR("NPR", "Nepalese Rupee", "₨"),
    NZD("NZD", "New Zealand Dollar", "$"),
    OMR("OMR", "Rial Omani", "﷼"),
    PAB("PAB", "USD Balboa US Dollar", "B/."),
    PEN("PEN", "Nuevo Sol", "S/."),
    PGK("PGK", "Kina", ""),
    PHP("PHP", "Philippine Peso Php", "Php"),
    PKR("PKR", "Pakistan Rupee", "₨"),
    PLN("PLN", "Zloty", "zł"),
    PYG("PYG", "Guarani", "Gs"),
    QAR("QAR", "Qatari Rial", "﷼"),
    RON("RON", "New Leu lei", "lei"),
    RSD("RSD", "Serbian Dinar", "Дин."),
    RUB("RUB", "Russian Ruble", "руб"),
    RWF("RWF", "Rwanda Franc", ""),
    SAR("SAR", "Saudi Riyal", "﷼"),
    SBD("SBD", "Solomon Islands Dollar", "$"),
    SCR("SCR", "Seychelles Rupee", "₨"),
    SDG("SDG", "Sudanese Pound", ""),
    SEK("SEK", "Swedish Krona", "kr"),
    SGD("SGD", "Singapore Dollar", "$"),
    SHP("SHP", "Saint Helena Pound", "£"),
    SLL("SLL", "Leone", ""),
    SOS("SOS", "Somali Shilling", "S"),
    SRD("SRD", "Surinam Dollar", "$"),
    STD("STD", "Dobra", ""),
    SVC("SVC", "El Salvador Colon US Dollar", "$"),
    SYP("SYP", "Syrian Pound", "£"),
    SZL("SZL", "Lilangeni", ""),
    THB("THB", "Baht", "฿"),
    TJS("TJS", "Somoni", ""),
    TMT("TMT", "Manat", ""),
    TND("TND", "Tunisian Dinar", ""),
    TOP("TOP", "Pa'anga", ""),
    TRY("TRY", "Turkish Lira", "TL"),
    TTD("TTD", "Trinidad and Tobago Dollar", "TT$"),
    TWD("TWD", "New Taiwan Dollar", "NT$"),
    TZS("TZS", "Tanzanian Shilling", ""),
    UAH("UAH", "Hryvnia", "₴"),
    UGX("UGX", "Uganda Shilling", ""),
    USD("USD", "US Dollar", "$"),
    USDC("USDC", "Coin", ""),
    USDT("USDT", "Tether", ""),
    UYU("UYU", "Peso Uruguayo Uruguay Peso en Unidades Indexadas", "$U"),
    UZS("UZS", "Uzbekistan Sum", "лв"),
    VEF("VEF", "Bolivar Fuerte", "Bs"),
    VND("VND", "Dong", "₫"),
    VUV("VUV", "Vatu", ""),
    WST("WST", "Tala", ""),
    XAF("XAF", "CFA Franc BEAC", ""),
    XAG("XAG", "Silver", ""),
    XAU("XAU", "Gold", ""),
    XBA("XBA", "Bond Markets Units European Composite Unit (EURCO)", ""),
    XBB("XBB", "European Monetary Unit (E.M.U.-6)", ""),
    XBC("XBC", "European Unit of Account 9(E.U.A.-9)", ""),
    XBD("XBD", "European Unit of Account 17(E.U.A.-17)", ""),
    XCD("XCD", "East Caribbean Dollar", "$"),
    XDR("XDR", "SDR", ""),
    XFU("XFU", "UIC-Franc", ""),
    XOF("XOF", "CFA Franc BCEAO", ""),
    XPD("XPD", "Palladium", ""),
    XPF("XPF", "CFP Franc", ""),
    XPT("XPT", "Platinum", ""),
    XTS("XTS", "Codes specifically reserved for testing purposes", ""),
    YER("YER", "Yemeni Rial", "﷼"),
    ZAR("ZAR", "Rand", "R"),
    ZMK("ZMK", "Zambian Kwacha", ""),
    ZWL("ZWL", "Zimbabwe Dollar", "Z$");

    private final String code;

    private final String name;

    private final String symbol;

    Currency(String code, String name, String symbol) {
        this.code = code;
        this.name = name;
        this.symbol = symbol;
    }

    @Override
    public String toString() {
        return name;
    }

    public CurrencyResponse toResponse() {
        var response = new CurrencyResponse();
        response.setCode(code);
        response.setName(name);
        response.setSymbol(symbol);

        return response;
    }
}
